In [ ]:
#Look for tickers with upcoming earnings(max days in advance parameter)

#Look at HV/IV ratio, look for absolue IV

#Compare expected move to historical moves
  #Expected move, find nearest expiry compute 1D straddle
    #1 day straddle calculation look at days and hours (if current time is within trading day)

#Have option to add constraints
  #HV/IV
  #Absolute IV
  #Liquidity constraints (B-A/Premium)
  #Premium constraints
  #Earnings performance of similar stocks

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import sys
sys.path.insert(0, '/OptionsEarningsScreen')

import OptionsEarningsTools as oet
import FinanceScrapers as fs
import FinanceTools as ft
import yfinanceHelper as yfh

In [ ]:
priceSeries = yfh.getYfTicker('DOCU').history(period = '1y')['Close']
ft.getHistoricalVolatility(priceSeries, days = 30)[-1]

0.36703243149604614

In [3]:
oet.getEarningsScreen('ORCL', earningsTime='PM', displayEarningsTable=True)

,EPS Estimate,Reported EPS,Surprise(%),1D Move,SPX 1D Move
Earnings Date,,,,,
2024-12-09 17:00:00,NaN,NaN,NaN,NaN,NaN
2024-09-09 17:00:00,NaN,NaN,NaN,NaN,NaN
2024-06-10 17:00:00,NaN,NaN,NaN,NaN,NaN
2024-03-11 17:00:00,1.26,NaN,NaN,NaN,NaN
2024-03-11 17:00:00,1.26,NaN,NaN,NaN,NaN
2023-12-11 17:00:00,1.32,1.34,0.0124,-0.132824,0.004589
2023-09-11 17:00:00,1.15,1.19,0.0382,-0.144972,-0.005712
2023-06-12 17:00:00,1.58,1.67,0.0552,0.002145,0.006909
2023-03-09 17:00:00,1.20,1.22,0.0150,-0.032763,-0.014584
2022-12-12 17:00:00,1.18,1.21,0.0268,-0.008898,0.007263
2022-09-12 17:00:00,1.07,1.03,-0.0390,-0.013584,-0.044199
2022-06-13 17:00:00,1.37,1.54,0.1234,0.099064,-0.003781
2022-03-10 17:00:00,1.18,1.13,-0.0387,0.015149,-0.013046

,Symbol,CurrentPrice,EarningsDate,EarningsTime,AvgAbs1DMove,Implied1DMove,Positive1DMoves,ReportedQuarters,HVOL_30D,ATM_VOL
0,ORCL,114.475,2024-03-11,PM,0.056175,0.118663,3,8,0.242366,0.963367

In [ ]:
from datetime import datetime, timedelta
startDate = datetime.today()
endDate = datetime.today()+timedelta(days=2)
minMarketCap = 10000000000
UE = oet.getUpcomingEarnings(startDate, endDate, minMarketCap, universe = None)
#UE.fillna(0, inplace=True)

ERROR:yfinance:BF.B: No earnings dates found, symbol may be delisted

TypeError: 'NoneType' object is not subscriptable

In [ ]:
UE

NameError: name 'UE' is not defined

In [ ]:
UE["ATM_VOL_HVOL_diff"] = (UE["ATM_VOL"]-UE["HVOL_30D"])/UE["HVOL_30D"]
UE.sort_values(by = "rank", ascending = True)

UE["same_day_diff"] = (UE["AvgAbs1DMove"]-UE["Implied1DMove"])
#UE.sort_values(by = "rank_2", ascending = False)

KeyError: 'rank'

In [ ]:
UE[UE["EarningsTime"] == "PM"]

,Symbol,CurrentPrice,EarningsDate,EarningsTime,AvgAbs1DMove,Implied1DMove,Positive1DMoves,ReportedQuarters,HVOL_30D,ATM_VOL,ATM_VOL_HVOL_diff,rank_order
2,VRTX,429.5200,2024-04-29,PM,0.036467,0.082864,5,8,0.185709,0.332087,0.788215,7.0
4,TM,202.9200,2023-10-31,PM,0.022432,0.044872,11,0,0.182781,0.325088,0.778572,6.0
6,AMGN,323.1350,2024-02-06,PM,0.029172,0.059198,4,8,0.183579,0.480271,1.616154,16.0
7,UBS,29.8650,2023-11-06,PM,0.049478,0.068074,8,11,0.200025,0.449933,1.249391,13.0
9,DIS,97.0125,2024-02-06,PM,0.055876,0.071036,4,8,0.205311,0.615653,1.998637,22.0
14,UL,49.3050,2023-10-25,PM,0.020946,NaN,10,0,0.129760,0.297310,1.291235,14.0
19,CSCO,49.4550,2024-02-14,PM,0.059944,0.073752,6,8,0.163236,0.429151,1.629022,17.0
20,TTE,64.0400,2023-10-25,PM,0.017259,0.018995,5,12,0.196674,0.245527,0.248398,4.0
22,AMAT,171.1700,2024-02-15,PM,0.026141,0.056891,3,8,0.333340,0.451848,0.355518,5.0

In [ ]:
UE['rank_order'] = UE['ATM_VOL_HVOL_diff'].rank(method='first', ascending=True)
UE['rank_order_2'] = UE['same_day_diff'].rank(method='first', ascending=True)
UE['average_rank'] = (UE['rank_order'] + UE['rank_order_2']) / 2

UE.sort_values(by = "average_rank", ascending = True)

KeyError: 'same_day_diff'